# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "testReleaseUnitTest")
    gradle(task: "connectedAndroidTest")
  end

  desc "Update version"
  lane :updateVersion do
    File.open("../app/build.gradle", "r") do |f|
      f.each_line do |line|
        if line.include? "versionName"
          print "Current version: ", line.split(" ")[1], "\n"
        end
      end
    end

    new_version = prompt(text: "New version number: ")
    android_set_version_code(
      gradle_file: "app/build.gradle",
      version_code: android_get_version_code(gradle_file: "app/build.gradle").to_i + 1,
    )
    android_set_version_name(
      gradle_file: "app/build.gradle",
      version_name: new_version,
    )
  end

  desc "Update screenshots"
  lane :screenshots do
    capture_android_screenshots
  end

  desc "Build release bundle for Google Play"
  lane :buildPlaystore do
    password = prompt(
      text: "Signing password for Google Play: ",
      secure_text: true
    )
    gradle(
      task: "clean bundle",
      build_type: 'Release',
      print_command: true,
      properties: {
        "android.injected.signing.store.file" => File.expand_path("../../release.jks"),
        "android.injected.signing.store.password" => password,
        "android.injected.signing.key.alias" => "key0",
        "android.injected.signing.key.password" => password,
      }
    )
    last_tag_name = sh("git describe --tags `git rev-list --tags --max-count=1`").strip
    apk_source_path = "../app/build/outputs/bundle/release/app-release.aab"
    apk_destination_path = "../babybuddy-for-android-#{last_tag_name}.aab"
    FileUtils.mv(apk_source_path, apk_destination_path)
    UI.message("APK moved and renamed to #{apk_destination_path}")
  end
  
  desc "Build release apk for GitHub"
  lane :buildGithub do
    password = prompt(
      text: "Signing password for GitHub release: ",
      secure_text: true
    )
    gradle(
      task: "clean assemble",
      build_type: 'Release',
      print_command: true,
      properties: {
        "android.injected.signing.store.file" => File.expand_path("../../release-personal.jks"),
        "android.injected.signing.store.password" => password,
        "android.injected.signing.key.alias" => "key0",
        "android.injected.signing.key.password" => password,
      }
    )
    last_tag_name = sh("git describe --tags `git rev-list --tags --max-count=1`").strip
    apk_source_path = "../app/build/outputs/apk/release/app-release.apk"
    apk_destination_path = "../babybuddy-for-android-#{last_tag_name}.apk"
    FileUtils.mv(apk_source_path, apk_destination_path)
    UI.message("APK moved and renamed to #{apk_destination_path}")
  end
end
