name: CI checks

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.12

      - name: Install Pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Set up JDK 18
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '18'
          distribution: 'temurin' # Note to self: This IS OpenJDK
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.2

      - name: Check build prerequisites
        run: |
          bash check-build-prerequisites.sh

      - name: Run make command
        run: |
          make -f help.makefile

      - name: Run check-translations.sh
        run: |
          bash tools/workflows/check-translations.sh
