name: CI checks

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.12

      - name: Install Pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Run make command
        run: |
          make -f help.makefile

      - name: Run check-translations.sh
        run: |
          bash tools/workflows/check-translations.sh
